---

title: "Windows ARM software"
subtitle: "‎Home"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

message:
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Note"
  icon: "fa fa-house"
  content: "This website is a collection of native programs for Windows on ARM architecture. <br /> The list is not full, contribute on Github by adding more apps to the list."

links:
  - name: "Home"
    icon: "fa-sharp fa-solid fa-house"
    url: ""

  - name: "FAQ"
    icon: "fa fa-question"
    url: "#faq"

  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/arminask/windows-arm-apps"
    target: "_blank" # optional html a tag target attribute 

  - name: "Resources"
    icon: "fa-solid fa-gear"
    url: "#resources"

# Services
services:
  - name: "Web Browsers"
    desc: "Web Browsers is a software application designed for various tasks."
    icon: "fa-brands fa-internet-explorer"
    items:
      - name: "Google Chrome"
        desc: "Google Chrome is a software application designed for various tasks."
        logo: "assets/tools/chrome.png"
        url: "https://www.google.com/chrome/?platform=win_arm64"
        target: "_blank" # optional html a tag target attribute

      - name: "Mozilla Firefox"
        desc: "Mozilla Firefox is a software application designed for various tasks."
        logo: "assets/tools/firefox.png"
        url: "https://www.mozilla.org/firefox/all/#product-desktop-release"
        target: "_blank" # optional html a tag target attribute

      - name: "Microsoft Edge"
        desc: "Microsoft Edge is a software application designed for various tasks."
        logo: "assets/tools/edge.png"
        url: "https://apps.microsoft.com/detail/xpfftq037jwmhs"
        target: "_blank" # optional html a tag target attribute

      - name: "Brave Browser"
        desc: "Brave Browser is a software application designed for various tasks."
        logo: "assets/tools/brave.png"
        url: "https://laptop-updates.brave.com/latest/winarm64"
        target: "_blank" # optional html a tag target attribute

      - name: "Chromium"
        desc: "Chromium is a software application designed for various tasks."
        logo: "assets/tools/chromium.png"
        url: "https://chromium.woolyss.com/#windows-on-arm"
        target: "_blank" # optional html a tag target attribute
        
      - name: "SRWare Iron"
        desc: "SRWare Iron is a software application designed for various tasks."
        logo: "assets/tools/iron.png"
        url: "https://www.srware.net/forum/viewforum.php?f=18"
        target: "_blank" # optional html a tag target attribute
       
      - name: "Thorium"
        desc: "Thorium is a software application designed for various tasks."
        logo: "assets/tools/thorium.png"
        url: "https://github.com/Alex313031/Thorium-WOA/releases"
        target: "_blank" # optional html a tag target attribute
       
      - name: "Bluebird"
        desc: "Bluebird is a software application designed for various tasks."
        logo: "assets/tools/bluebird.png"
        url: "https://apps.microsoft.com/detail/9pnxw61t4t0v"
        target: "_blank" # optional html a tag target attribute

      - name: "Vivaldi"
        desc: "Vivaldi is a highly customizable browser that offers advanced features like tab stacking and keyboard shortcuts."
        logo: "assets/tools/Vivaldi.png"
        subtitle: "Experimental builds"
        url: "https://vivaldi.com/blog/desktop/memory-saver-and-compact-menus-vivaldi-browser-snapshot-3329-7/#win_arm64"
        target: "_blank" # optional html a tag target attribute
       
      - name: "Midori"
        desc: "Midori is a lightweight, fast web browser that focuses on simplicity and speed, ideal for older systems."
        logo: "assets/tools/midori.png"
        url: "https://astian.org/midori-browser/download/windows/"
        target: "_blank" # optional html a tag target attribute

      - name: "Opera"
        desc: "Opera is a Chromium-based browser with built-in VPN and other features for Windows."
        logo: "assets/tools/opera.png"
        subtitle: "Developer builds"
        url: "https://www.opera.com/browsers/opera/developer"
        target: "_blank" # optional html a tag target attribute
